version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sto-server-status
    hostname: oscr-server-status
    restart: always
    env_file: .env
    volumes:
      - ./data:/opt/data:rw

